config/routes.rb
Rails.application.routes.draw do

  get 'comments/edit'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'

  end

  root 'home#top'
  resources :users
  resources :posts do
    resources :comments
  end

  delete '/posts/:id/destroy' => 'posts#destroy'


end

# Mysql：DB portfolio_two_development

# Prefix Verb   URI Pattern                                                                                       Controller#Action
# comments_edit GET    /comments/edit(.:format)                                                                          comments#edit
# new_user_session GET    /users/sign_in(.:format)                                                                          users/sessions#new
#  user_session POST   /users/sign_in(.:format)                                                                          users/sessions#create
# destroy_user_session DELETE /users/sign_out(.:format)                                                                         users/sessions#destroy
# new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
# edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
# user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#               PUT    /users/password(.:format)                                                                         devise/passwords#update
#               POST   /users/password(.:format)                                                                         devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                                                                           users/registrations#cancel
# new_user_registration GET    /users/sign_up(.:format)                                                                          users/registrations#new
# edit_user_registration GET    /users/edit(.:format)                                                                             users/registrations#edit
# user_registration PATCH  /users(.:format)                                                                                  users/registrations#update
#               PUT    /users(.:format)                                                                                  users/registrations#update
#               DELETE /users(.:format)                                                                                  users/registrations#destroy
#               POST   /users(.:format)                                                                                  users/registrations#create
# users_sign_out GET    /users/sign_out(.:format)                                                                         devise/sessions#destroy
#          root GET    /                                                                                                 home#top
#         users GET    /users(.:format)                                                                                  users#index
#               POST   /users(.:format)                                                                                  users#create
#      new_user GET    /users/new(.:format)                                                                              users#new
#     edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
#          user GET    /users/:id(.:format)                                                                              users#show
#               PATCH  /users/:id(.:format)                                                                              users#update
#               PUT    /users/:id(.:format)                                                                              users#update
#               DELETE /users/:id(.:format)                                                                              users#destroy
# post_comments GET    /posts/:post_id/comments(.:format)                                                                comments#index
#               POST   /posts/:post_id/comments(.:format)                                                                comments#create
# new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                            comments#new
# edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format)                                                       comments#edit
#  post_comment GET    /posts/:post_id/comments/:id(.:format)                                                            comments#show
#               PATCH  /posts/:post_id/comments/:id(.:format)                                                            comments#update
#               PUT    /posts/:post_id/comments/:id(.:format)                                                            comments#update
#               DELETE /posts/:post_id/comments/:id(.:format)                                                            comments#destroy
#         posts GET    /posts(.:format)                                                                                  posts#index
#               POST   /posts(.:format)                                                                                  posts#create
#      new_post GET    /posts/new(.:format)                                                                              posts#new
#     edit_post GET    /posts/:id/edit(.:format)                                                                         posts#edit
#          post GET    /posts/:id(.:format)                                                                              posts#show
#               PATCH  /posts/:id(.:format)                                                                              posts#update
#               PUT    /posts/:id(.:format)                                                                              posts#update
#               DELETE /posts/:id(.:format)                                                                              posts#destroy
#               DELETE /posts/:id/destroy(.:format)                                                                      posts#destroy
# rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
# rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
# rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
# rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
# rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
# rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
# rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#               POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
# new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
# edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                                 rails/conductor/action_mailbox/inbound_emails#edit
# rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
#               PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#update
#               PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#update
#               DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#destroy
# new_rails_conductor_inbound_email_source GET    /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
# rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
# rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :comments, dependent: :destroy

    validates :title, :content, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  protect_from_forgery :except => [:destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: '新しく投稿しました！'
    else
      flash[:alert] = "投稿ができませんでした"
      render :new
    end
  end

  def user
    User.find(id: self.user_id)
  end

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: '投稿を編集しました！'
    else
      flash[:alert] = "編集ができませんでした"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: '投稿を削除しました'
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="posts-form">
    <%= form_with model: @post, local: true do |f| %>
        <label class="title">タイトル</label>
        <div class="content cmn-textarea">
            <%= f.text_field :title, class: "form-control" %>
        </div>
        <label class="title">内容</label>
        <div class="content cmn-textarea">
            <%= f.text_area :content, class: "form-control", size: "60x10" %>
        </div>
        <div class="btn btn-posts">
            <%= f.submit "投稿する", class: "btn" %>
        </div>
    <% end %>
</div>

app/views/posts/edit.html.erb
<div class="cmn">
    <p class="url">Find me in app/views/posts/edit.html.erb</p>
    <h2 class="cmn-title">投稿編集</h2>
    <div class="col-md-12">
        <%= render 'form' %>
    </div>
</div>

app/views/posts/index.html.erb
<div class="cmn posts-index">
    <p class="url">Find me in app/views/posts/index.html.erb</p>
    <h2 class="cmn-title">投稿一覧</h2>
    <div class="index">
        <% @posts.each do |post| %>
            <% if post.present? %>
                <div class="item">
                    <p class="text">投稿者</p>
                    <%= link_to post.user.username, user_path(post.user_id) %></p>
                    <p class="text">タイトル</p>
                    <%= link_to post.title, post_path(post.id) %>
                    <p class="text">投稿内容</p>
                    <%= link_to post.content, post_path(post.id) %>
                </div>
            <% else %>
                <P>投稿はありません</p>
            <% end %>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<div class="cmn">
    <p class="url">Find me in app/views/posts/new.html.erb</p>
    <h2 class="cmn-title">新規投稿</h2>

    <div class="post-form">
        <%= render 'form' %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="cmn posts-show">
    <p class="url">Find me in app/views/posts/show.html.erb</p>
    <h2 class="cmn-title"><%= @post.title %></h2>
    <div class="content">
        <div class="img-icon">
            <% if @post.user.image? %>
                <%= image_tag @post.user.image.url %>
            <% else %>
                <%= image_tag "/assets/default.jpg", :size => '250x250' %>
            <% end %>
        </div>
        <div class="name">
            投稿者: <%= @post.user.username %>
        </div>
        <div class="content">
            内容: <%= @post.content %>
        </div>
    </div>
    <div class="current_user">
        <% if @post.user == current_user %>
            <%= link_to '●投稿の編集', edit_post_path(@post.id) %>
            <br>
            <%= link_to "●削除する", post_path(@post), method: :delete, data: {confirm: "本当に削除しますか？"} %>
        <% end %>
    </div>
    <div class="comment">
        <h3 class="cmn-subtitle">□この投稿に対するコメント</h3>
        <div class="comment-container">
            <% if @post.comments.any? %>
                <div class="item">
                    <% @post.comments.each do |comment| %>
                        <div class="name">
                            <p>名前 : <%= comment.name %></p>
                        </div>
                        <div class="desc">
                            <p>コメント : <%= comment.content %></p>
                        </div>
                        <div class="menu">
                            <%= link_to '●コメント編集', edit_post_comment_path(@post, comment) %>
                            <%= link_to '●コメント削除', post_comment_path(@post, comment), method: :delete, data: {confirm: "本当に削除しますか？"} %>
                        </div>
                    <% end %>
                </div>
            <% else %>
                <p>この投稿に対するコメントはありません</p>
            <% end %>
        </div>
        <div class="comment-form">
            <h3 class="cmn-subtitle">□コメントを投稿する</h3>
            <%= form_with model: [@post, @comment], local: true do |f| %>
                <%= f.hidden_field :post_id, { value: @post.id} %>
                <div class="com-field">
                    <label class="title">名前</label>
                    <div class="content">
                        <%= f.text_field :name, class: 'com-form' %>
                    </div>
                </div>
                <div class="com-field">
                    <label class="title">コメント</label>
                    <div class="content">
                        <%= f.text_area :content, class: 'com-form', size: "60x10"  %>
                    </div>
                </div>
                <div class="btn-com">
                    <%= f.submit "コメントする", class: 'btn' %>
                </div>
            <% end %>
        </div>
    </div>
</div>